"""Fix foreign key on list table to point to board.id

Revision ID: 80f92372c34d
Revises: 
Create Date: 2025-09-15 22:35:05.483248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80f92372c34d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'order',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('list', 'order',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('list_ibfk_1'), 'list', type_='foreignkey')
    op.create_foreign_key(None, 'list', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list', type_='foreignkey')
    op.create_foreign_key(op.f('list_ibfk_1'), 'list', 'board', ['board_id'], ['user_id'])
    op.alter_column('list', 'order',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('card', 'order',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
